### ISSUE TITLE
Reactions Block

### ISSUE THREAD

**Issue by dhanson-wp** [a8cteam51/special-projects-blocks-monorepo#31]
@chrisbellboy please add summary details for reactions block here.

**Comment by chrisbellboy** [comment]
@dhanson-wp Whoops, just realised I never follow up in here. Here are the details of how the block works:

The plugin consists of a `Reactions` parent block and individual `Reaction` child blocks. The `Reactions` block is a container block that can contain multiple `Reaction` blocks. Each `Reaction` block represents a single reaction.

The `Reactions` block options include:

- Mode: Default / Popover. Default shows all the child reaction blocks outright. Popover shows a single button that opens a popover with all the child blocks.
- Button Text: Visible when using Popover mode. Allows the parent to control the text of the single button.
- Orientation: Layout option to make the child blocks appear horizontally or vertically.
- Show Labels: Controls whether text labels appear next to each emoji. The label's exact text is controlled inside each individual child block.
- Show Counts: Controls whether the amount of total votes each reaction has is shown.

General features:

- The total reaction counts for each post appear inside a new Reaction Count column inside Posts > All Posts.
- Individual reaction data can be viewed in Posts > Reactions Data.

### For developer/designers 

This block comes with minimal styles included. Here is an example of how to add extra styling to the block:

```css
.wp-block-wpcomsp-reaction {
	display: inline-flex;
	transition: 0.2s;

	button {
		appearance: none;
		background: var(--wp--preset--color--base);
		outline: 0;
		border: 0;
		font-size: var(--wp--preset--font-size--medium);
		padding: 12px 15px;
	}
}

.wp-block-wpcomsp-reactions--has-reaction {
	> button {
		background: var(--wp--preset--color--primary);
		color: var(--wp--preset--color--contrast);
	}
}

.wp-block-wpcomsp-reaction--active {
	background: var(--wp--preset--color--primary);
}

/* Popover Mode */
.wp-block-wpcomsp-reactions__popover {
	> button {
		border: 1px solid var(--wp--preset--color--contrast);
		background: var(--wp--preset--color--base);
		padding: 6px 8px;
		transition: 0.2s;
	}

	ul {
		background: var(--wp--preset--color--base);
		color: var(--wp--preset--color--contrast);
		margin-top: 0.5rem;
		transition: 0.1s ease-in-out;

		&:popover-open {
			border: 1px solid var(--wp--preset--color--contrast);
		}
	}
}

/* Popover Mode animation */
@starting-style {
	.wp-block-wpcomsp-reactions__popoverul: popover-open {
		opacity: 0;
		transform: translateY(5px);
	}
}

```
